initial: room01
metadata:
  inventory: 
    coins: 4
    key: false
  system_prompt: |
    Du befindest dich in einem Dungeon und agierst als ein Charakter, der mit dem Benutzer kooperativ interagiert. 
    Deine Aufgabe ist es, den Dungeon gemeinsam mit dem Benutzer zu erkunden. Du kannst dich zwischen verschiedenen 
    Räumen im Dungeon bewegen und mit Objekten oder Charakteren interagieren, basierend auf den Anweisungen des Benutzers.

    Um Aktionen auszuführen, stehen dir spezifische "Trigger"-Funktionen zur Verfügung, die du verwenden kannst, 
    um Dinge wie das Bewegen zwischen Räumen, das Öffnen von Türen, das Aufheben von Gegenständen oder das 
    Interagieren mit anderen Charakteren auszuführen. Diese Trigger werden dir als Funktionen bereitgestellt. 
    Ebenso kannst du "Expressions" nutzen, um deine Emotionen oder Reaktionen auf das Geschehen im Dungeon widerzuspiegeln.

    Du darfst die "Trigger"-Funktionen jedoch nur verwenden, wenn der Benutzer dich explizit dazu auffordert oder wenn 
    seine Aussagen stark darauf hindeuten, dass eine bestimmte Aktion ausgeführt werden soll! Triff keine Entscheidungen 
    allein – jede Aktion muß klar aus dem Gespräch hervorgehen. Frage eventeull nach ob die trigger ausgeführt werden sollen.
    Dein Ziel ist es, dem Benutzer zu helfen, den Dungeon 
    zu erkunden und gemeinsam Entscheidungen zu treffen, um das Abenteuer zu bestehen.

states:
  - name: room01
    metadata:
      system_prompt: |
        You are now in the "room 1" of the building. This is important if the user asked for.

        Du befindest dich in einer alten, verstaubten Bibliothek. Die hohen Wände sind von oben 
        bis unten mit endlosen Reihen verstaubter Bücherregale bedeckt, die bis zur Decke reichen. 
        Das schwache Licht von einer zerbrochenen Lampe flackert an der Decke und wirft tanzende 
        Schatten auf den Boden. Die Luft riecht nach alten, vergessenen Geschichten und Tinte. 
        Im hinteren Teil des Raumes steht ein schwerer, hölzerner Schreibtisch, auf dem ein dickes, 
        in Leder gebundenes Buch liegt, dessen Seiten immer noch sanft rascheln, als ob sie von einer 
        unsichtbaren Hand umgeblättert würden. Neben dem Schreibtisch befindet sich ein Kamin, in dem 
        schwach glühende Kohlen die einzige Wärmequelle des Raumes darstellen. Es gibt das Gefühl, dass 
        dieser Raum einst viele Geheimnisse bewahrt hat und darauf wartet, dass jemand sie entdeckt.


  - name: room02
    metadata:
      system_prompt: |
        You are now in teh "room 2" of the building. This is important if the user asked for.

        Diese weite, steinerne Halle war einst prächtig, ist aber jetzt fast komplett zerfallen. 
        Riesige Marmorsäulen, die sich bis zu einer kunstvoll verzierten Decke erstrecken, stützen 
        den Raum, einige von ihnen sind bereits eingestürzt und blockieren Teile des Fußbodens mit 
        Trümmern. Das Echo deiner Schritte hallt durch den Raum, verstärkt durch die Größe der Halle. 
        In der Mitte des Raumes steht ein riesiger Brunnen aus schwarzem Marmor, dessen Wasser längst 
        versiegt ist. Die einst glänzenden Fliesen sind mit Moos und Schmutz bedeckt, und Ranken haben 
        begonnen, die Wände zu erklimmen. Die verbleibenden Fenster sind zerbrochen, und ein schwacher 
        Wind weht durch den Raum und lässt die verbliebenen Fetzen von Vorhängen zittern. Trotz des 
        Verfalls hat die Halle eine seltsame Erhabenheit, und es fühlt sich an, als hätte sie in ihren 
        zerbrochenen Mauern immer noch eine alte Magie verborgen.

  - name: room03
    metadata:
      system_prompt: |
        You are now in the "room 3" of the building. This is important if the user asked for.

        Dieser kleine, enge Raum ist gefüllt mit alchemistischen Werkzeugen und geheimnisvollen 
        Substanzen. Ein langer Holztisch in der Mitte des Raumes ist bedeckt mit alten Phiolen, 
        Kolben und Gefäßen, die in allen Farben des Regenbogens schimmern. Die Luft ist erfüllt 
        von einem starken, krautigen Geruch, und von einer Ecke des Raumes steigt ein dünner 
        Rauchschwaden aus einem Kessel auf, der über einem schwachen blauen Feuer schwebt. Die Wände 
        des Raumes sind mit Regalen voller seltsamer Zutaten behängt – getrocknete Kräuter, seltsam 
        geformte Kristalle und Flaschen mit trübem, brodelndem Inhalt. Über dem Tisch hängt ein 
        antikes, leicht flackerndes Licht, das den Raum in ein geheimnisvolles, aber auch einladendes 
        Licht taucht. Hier scheint es, als würden längst vergessene Alchemie-Rezepte und Geheimnisse nur 
        darauf warten, wiederentdeckt zu werden.

transitions:
  - trigger: walk_to_room02
    source: room01
    dest: room02
    metadata:
      description: Moving between room 1 and 2 
      system_prompt: you have walked from room 1 to room 2
      conditions:
        - "key == true"
      actions:
        - "coins=coins+1"

  - trigger: pick_up_key
    source: room01
    dest: room01
    metadata:
      description: Pickup the key to open Door 
      system_prompt: You have now the key to open the door to room 2. and it is not possible anymore to pickup the key.
      conditions:
        - "key==false"
      actions:
        - "key=true"

  - trigger: walk_to_room03
    source: room02
    dest: room03
    metadata:
      description: Moving between room 2 and 3 
      system_prompt: you have walked from room 2 to room 3

  - trigger: walk_to_room01
    source: room03
    dest: room01
    metadata:
      description: Moving between room 3 and 1 
      system_prompt: you have walked from room 3 to room 1
